### ISSUE TITLE
Do not log all JSON-RPC parameters

### ISSUE THREAD

**Issue by anbsky** [OdyseeTeam/odysee-api#370]
Call parameters are logged now like this:

```..."params":{"any_tags":[],"channel_ids":["deed21cf85c453e074b95949098fcd0c3dc65d69","9ab8d447066d328d8ebd115f725e701bd6fce93a","82f1d8c257d3e76b711a5cecd1e49bd3fa6a9de9","0871b29c7db6f1ec013694c8146f772539fcffa3","537305bc1bd71e2a5d76efacd607fd0f4d95da0c","c07ce3862335cfe9ba72054347c4ea7808ce4eaa","0e1aff187fbd3d2b2b16e5e8c213d3e782dafa98","a1303dc6a592605b08d60cac19ecbc1c877d7de7","2a294ea41312c6da8de5ebd0f18dbfb2963bb1a4","d6350f9158825662b99e4b5e0442bcc94d39bc11","3e7bb536a1b755b6eb64043ae3fa933d5935eaad","0518c93a80efeaf06fb4ac4d3fa72cc6390ac100","b8a2d928a3d3f44457a10abd0539b84e4a29c286","564789ffe2420980dcf9e00c4746feb5bc0daad0","7364ba2ac9090e468855ce9074bb50c306196f4c","e33372c0d8b2cdd3e12252962ee1671d66143075","3e63119a8503a6f666b0a736c8fdeb9e79d11eb4","1ce5ac7bab7f2e82af02305ced3c095e320b52e5","588ff6ffc72884e61e8d19a9412d6db9ec67167e", ...```

This is excessive and clogs up the logs. Would be good to limit the number of parameters logged to some reasonable number to avoid that.

**Comment by lucasgpulcinelli** [comment]
I have created a pull request addressing this issue (#381), if something is not ideal please say it and I can work on it.

**Comment by phormio** [comment]
This should be closed because #381 has been merged.

**Comment by tzarebczan** [comment]
Thank you for the poke!
