### ISSUE TITLE
How to get the auth token?

### ISSUE THREAD

**Issue by trueauracoral** [OdyseeTeam/odysee-api#404]
Hello there. We have found out how to sync a wallet using the auth token, email, and password of a user with a small Python script that can be found [here](https://codeberg.org/vertbyqb/libbry/issues/14). The problem is many users do not know their auth token, only their email and password, so they must go into inspect element in a browser and find it manually through the calls the browser makes. Is there any way to get the auth token through the Odysee API? Thanks.

**Comment by keikari** [comment]
The auth_token is created at line `auth_token = newStuff["data"]["auth_token"]` in the script. No need to enter it manually

**Comment by tzarebczan** [comment]
We have a way to show the auth token on odysee.com help page, but it does require a special tag. users can reach out to hello@odysee.com for now to get it. In the future tokens will be going away and replaced with authorization JWT objects, so we'll be doing more with third party support, etc.
