### ISSUE TITLE
Sync YouTube playlists

### ISSUE THREAD

**Issue by nesbocaj** [OdyseeTeam/odysee-api#405]
I'm not sure if this is the right repository in which to file this issue, but it would be neat if YouTube Sync included not just the creator's videos but also their playlists.

Especially since it seems that some creators don't interact with their Odysee profiles until they have been banned or otherwise excluded from YouTube, and instead use it as a backup for their content.

**Comment by tzarebczan** [comment]
This is not the right repo, we'll reopen on the proper one, but unlikely this gets worked on any time soon. Thank you for the suggestion!

**Comment by nesbocaj** [comment]
Thanks for letting me know, @tzarebczan, but which repository did you reopen it in?
