### ISSUE TITLE
[Marketing] Expand into social media

### ISSUE THREAD

**Issue by Myzel394** [OdyseeTeam/odysee-api#424]
I took a quick look at Odysee's YouTube channel (https://www.youtube.com/c/LBRYcom/videos) and TikTok account, but it's honestly pretty much nothing going on there.

I'd suggest to expand the social media presence on all mediums (YouTube, Instagram, TikTok, Twitter, Pixelfed, Mastodon) and to regularly post to get more attention. You'd probably want to hire some people that are specialized on this to make sure they upload regularly.

**Comment by andybeletsky** [comment]
Thank you for your input, however, this repo is only for things immediately related to odysee API.

**Comment by Myzel394** [comment]
@andybeletsky Where should stuff like this be placed to?

**Comment by andybeletsky** [comment]
Unfortunately our marketing team does not have a public repo for suggestions but we are present on Twitter and other social media.

**Comment by Myzel394** [comment]
@andybeletsky Could you forward this to them? 

> we are present on Twitter and other social media.

I just took a quick look at YouTube and TikTok. The last video on YouTube was uploaded almost a year ago and there's no content on TikTok.
