### ISSUE TITLE
support new rental tags

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-api#451]
Keep support for the existing tags, but also add: 
c:rental
c:purchase
c:preorder

We're adding those on top of c:rental:xxxx / c:purchase:xxxx/ c:preorder:xxxx so that the claim search in various areas can filter these out if needed. 

Also on the player side.

**Comment by anbsky** [comment]
We don't currently support pre-order tags neither on the player nor on the oapi side . What's the scneario for them?

**Comment by tzarebczan** [comment]
Just needs some better tests to support all scenarios, but this was done.
